export const CHAT_MARKDOWN_CLASS = [
  "text-sm leading-scaled-22px tracking-0 text-foreground font-[450]",
  "[&_p]:my-0 [&_p]:min-w-0 [&_p]:max-w-full [&_p]:text-sm [&_p]:leading-scaled-22px [&_p]:tracking-0 [&_p]:text-foreground [&_p]:font-[450] [&_p]:break-words [&_p]:[overflow-wrap:anywhere] [&_p+p]:mt-2.5",
  "[&_strong]:font-medium [&_strong]:text-foreground [&_[data-streamdown=strong]]:font-medium [&_[data-streamdown=strong]]:text-foreground [&_em]:text-foreground/90",
  "[&.chat-markdown--caret-off>*:last-child::after]:opacity-0",
  "[&_[data-streamdown=heading-1]]:mt-7 [&_[data-streamdown=heading-1]]:mb-2.5 [&_[data-streamdown=heading-1]]:text-2xl [&_[data-streamdown=heading-1]]:leading-scaled-30px [&_[data-streamdown=heading-1]]:font-semibold [&_[data-streamdown=heading-1]]:tracking-minus-0p018em [&_[data-streamdown=heading-1]]:text-foreground",
  "[&_[data-streamdown=heading-2]]:mt-6 [&_[data-streamdown=heading-2]]:mb-2 [&_[data-streamdown=heading-2]]:text-lg [&_[data-streamdown=heading-2]]:leading-scaled-26px [&_[data-streamdown=heading-2]]:font-semibold [&_[data-streamdown=heading-2]]:tracking-minus-0p012em [&_[data-streamdown=heading-2]]:text-foreground",
  "[&_[data-streamdown=heading-3]]:mt-5 [&_[data-streamdown=heading-3]]:mb-1.5 [&_[data-streamdown=heading-3]]:text-sm [&_[data-streamdown=heading-3]]:leading-scaled-22px [&_[data-streamdown=heading-3]]:font-semibold [&_[data-streamdown=heading-3]]:tracking-minus-0p006em [&_[data-streamdown=heading-3]]:text-foreground",
  "[&_[data-streamdown=heading-4]]:mt-4 [&_[data-streamdown=heading-4]]:mb-1 [&_[data-streamdown=heading-4]]:text-sm [&_[data-streamdown=heading-4]]:leading-scaled-22px [&_[data-streamdown=heading-4]]:font-semibold [&_[data-streamdown=heading-4]]:tracking-0 [&_[data-streamdown=heading-4]]:text-foreground [&_[data-streamdown=heading-5]]:mt-4 [&_[data-streamdown=heading-5]]:mb-1 [&_[data-streamdown=heading-5]]:text-sm [&_[data-streamdown=heading-5]]:leading-scaled-22px [&_[data-streamdown=heading-5]]:font-semibold [&_[data-streamdown=heading-5]]:text-foreground",
  "[&_[data-streamdown=heading-6]]:mt-4 [&_[data-streamdown=heading-6]]:mb-1 [&_[data-streamdown=heading-6]]:text-sm [&_[data-streamdown=heading-6]]:leading-scaled-20px [&_[data-streamdown=heading-6]]:font-semibold [&_[data-streamdown=heading-6]]:tracking-wide [&_[data-streamdown=heading-6]]:text-muted-foreground [&_[data-streamdown^=heading-]:first-child]:mt-0",
  "[&_[data-streamdown=link]]:rounded-xs [&_[data-streamdown=link]]:font-medium [&_[data-streamdown=link]]:text-sky-600 [&_[data-streamdown=link]]:no-underline [&_[data-streamdown=link]]:decoration-sky-500/45 [&_[data-streamdown=link]]:underline-offset-2 [&_[data-streamdown=link]]:transition-colors hover:[&_[data-streamdown=link]]:underline dark:[&_[data-streamdown=link]]:text-sky-400",
  "[&_[data-streamdown=inline-code]]:whitespace-pre-wrap [&_[data-streamdown=inline-code]]:break-words [&_[data-streamdown=inline-code]]:rounded-xs [&_[data-streamdown=inline-code]]:border-0 [&_[data-streamdown=inline-code]]:bg-foreground/[0.085] [&_[data-streamdown=inline-code]]:px-5px [&_[data-streamdown=inline-code]]:py-px [&_[data-streamdown=inline-code]]:font-mono [&_[data-streamdown=inline-code]]:text-[0.92em] [&_[data-streamdown=inline-code]]:font-normal [&_[data-streamdown=inline-code]]:leading-1p45 [&_[data-streamdown=inline-code]]:text-foreground/95 [&_[data-streamdown=inline-code]]:[overflow-wrap:anywhere]",
  "[&_[data-streamdown=code-block]]:relative [&_[data-streamdown=code-block]]:my-4 [&_[data-streamdown=code-block]]:w-full [&_[data-streamdown=code-block]]:min-w-0 [&_[data-streamdown=code-block]]:overflow-hidden [&_[data-streamdown=code-block]]:rounded-lg [&_[data-streamdown=code-block]]:border-0 [&_[data-streamdown=code-block]]:bg-foreground/[0.045] [&_[data-streamdown=code-block]]:p-0 [&_[data-streamdown=code-block]]:shadow-none [&_[data-streamdown=code-block]]:outline-none [&_[data-streamdown=code-block]]:ring-0",
  "[&_[data-streamdown=code-block-header]]:h-8 [&_[data-streamdown=code-block-header]]:border-0 [&_[data-streamdown=code-block-header]]:border-b [&_[data-streamdown=code-block-header]]:border-border/45 [&_[data-streamdown=code-block-header]]:bg-transparent [&_[data-streamdown=code-block-header]]:px-3 [&_[data-streamdown=code-block-header]]:py-0 [&_[data-streamdown=code-block-header]]:text-xs [&_[data-streamdown=code-block-header]]:font-medium [&_[data-streamdown=code-block-header]]:tracking-0 [&_[data-streamdown=code-block-header]]:text-muted-foreground/85 [&_[data-streamdown=code-block-header]]:shadow-none [&_[data-streamdown=code-block-header]>span]:ml-0 [&_[data-streamdown=code-block-header]>span]:font-sans [&_[data-streamdown=code-block-header]>span]:normal-case",
  "[&_[data-streamdown=code-block-body]]:w-full [&_[data-streamdown=code-block-body]]:min-w-0 [&_[data-streamdown=code-block-body]]:overflow-x-auto [&_[data-streamdown=code-block-body]]:rounded-none [&_[data-streamdown=code-block-body]]:border-0 [&_[data-streamdown=code-block-body]]:bg-transparent [&_[data-streamdown=code-block-body]]:p-0 [&_[data-streamdown=code-block-body]]:text-sm [&_[data-streamdown=code-block-body]]:shadow-none [&_[data-streamdown=code-block-body]]:outline-none [&_[data-streamdown=code-block-body]]:ring-0 [&_[data-streamdown=code-block-body]_pre]:leading-scaled-22px [&_[data-streamdown=code-block-body]_pre_code>span::before]:hidden [&_[data-streamdown=code-block-body]_pre_code>span::before]:content-none",
  "[&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]]:relative [&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]]:border-0 [&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]]:bg-transparent [&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]::after]:hidden [&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]_[data-streamdown=code-block-header]]:border-0 [&.chat-markdown--streaming_[data-streamdown=code-block][data-incomplete=true]_[data-streamdown=code-block-header]]:bg-transparent",
  "[&_[data-streamdown=blockquote]]:my-4 [&_[data-streamdown=blockquote]]:min-w-0 [&_[data-streamdown=blockquote]]:max-w-full [&_[data-streamdown=blockquote]]:border-l-2 [&_[data-streamdown=blockquote]]:border-border/75 [&_[data-streamdown=blockquote]]:pl-3.5 [&_[data-streamdown=blockquote]]:not-italic [&_[data-streamdown=blockquote]]:text-foreground/82 [&_[data-streamdown=blockquote]]:[overflow-wrap:anywhere] [&_[data-streamdown=blockquote]_p]:my-0 [&_[data-streamdown=blockquote]_p]:text-foreground/82",
  "[&_[data-streamdown=unordered-list]]:my-2 [&_[data-streamdown=unordered-list]]:ml-0 [&_[data-streamdown=unordered-list]]:list-outside [&_[data-streamdown=unordered-list]]:list-disc [&_[data-streamdown=unordered-list]]:space-y-1 [&_[data-streamdown=unordered-list]]:pl-5 [&_[data-streamdown=ordered-list]]:my-2 [&_[data-streamdown=ordered-list]]:ml-0 [&_[data-streamdown=ordered-list]]:list-outside [&_[data-streamdown=ordered-list]]:list-decimal [&_[data-streamdown=ordered-list]]:space-y-1 [&_[data-streamdown=ordered-list]]:pl-5",
  "[&_[data-streamdown=list-item]]:min-w-0 [&_[data-streamdown=list-item]]:max-w-full [&_[data-streamdown=list-item]]:break-words [&_[data-streamdown=list-item]]:py-0 [&_[data-streamdown=list-item]]:pl-0 [&_[data-streamdown=list-item]]:text-sm [&_[data-streamdown=list-item]]:leading-scaled-22px [&_[data-streamdown=list-item]]:font-[450] [&_[data-streamdown=list-item]]:[overflow-wrap:anywhere] [&_.contains-task-list]:list-none [&_.contains-task-list]:pl-0 [&_.task-list-item]:flex [&_.task-list-item]:items-start [&_.task-list-item]:gap-2 [&_.task-list-item]:pl-0 [&_.task-list-item_input[type=checkbox]]:mt-[0.28rem] [&_.task-list-item_input[type=checkbox]]:size-3.5 [&_.task-list-item_input[type=checkbox]]:accent-emerald-500",
  "[&_[data-streamdown=table-wrapper]]:my-4 [&_[data-streamdown=table-wrapper]]:w-full [&_[data-streamdown=table-wrapper]]:min-w-0 [&_[data-streamdown=table-wrapper]]:gap-0 [&_[data-streamdown=table-wrapper]]:rounded-none [&_[data-streamdown=table-wrapper]]:border-0 [&_[data-streamdown=table-wrapper]]:bg-transparent [&_[data-streamdown=table-wrapper]]:p-0 [&_[data-streamdown=table-wrapper]]:shadow-none [&_[data-streamdown=table-wrapper]>div:first-child]:justify-end [&_[data-streamdown=table-wrapper]>div:first-child]:gap-1 [&_[data-streamdown=table-wrapper]>div:first-child]:px-0 [&_[data-streamdown=table-wrapper]>div:last-child]:w-full [&_[data-streamdown=table-wrapper]>div:last-child]:min-w-0 [&_[data-streamdown=table-wrapper]>div:last-child]:overflow-x-auto [&_[data-streamdown=table-wrapper]_button]:rounded-md [&_[data-streamdown=table-wrapper]_button]:border-0 [&_[data-streamdown=table-wrapper]_button]:bg-transparent [&_[data-streamdown=table-wrapper]_button]:shadow-none hover:[&_[data-streamdown=table-wrapper]_button]:bg-foreground/[0.04]",
  // 大表格无折叠策略（代码块有 24 行预览，表格没有）：视口外的表格直接跳过
  // 布局与绘制。`auto` 关键字在首次渲染后记住真实尺寸，240px 仅为首渲前占位；
  // 旧 WebKit 不支持时静默忽略，行为退回现状。
  "[&_[data-streamdown=table-wrapper]]:[contain-intrinsic-size:auto_240px] [&_[data-streamdown=table-wrapper]]:[content-visibility:auto]",
  "[&_[data-streamdown=table]]:my-0 [&_[data-streamdown=table]]:w-full [&_[data-streamdown=table]]:min-w-full [&_[data-streamdown=table]]:table-auto [&_[data-streamdown=table]]:border-collapse [&_[data-streamdown=table]]:border-0 [&_[data-streamdown=table]]:bg-transparent [&_[data-streamdown=table]]:text-sm [&_[data-streamdown=table-header]]:bg-transparent [&_[data-streamdown=table-header-cell]]:border-0 [&_[data-streamdown=table-header-cell]]:border-b [&_[data-streamdown=table-header-cell]]:border-border/55 [&_[data-streamdown=table-header-cell]]:px-0 [&_[data-streamdown=table-header-cell]]:py-2 [&_[data-streamdown=table-header-cell]]:pr-8 [&_[data-streamdown=table-header-cell]]:text-left [&_[data-streamdown=table-header-cell]]:font-semibold [&_[data-streamdown=table-cell]]:border-0 [&_[data-streamdown=table-cell]]:border-b [&_[data-streamdown=table-cell]]:border-border/35 [&_[data-streamdown=table-cell]]:px-0 [&_[data-streamdown=table-cell]]:py-2 [&_[data-streamdown=table-cell]]:pr-8 [&_[data-streamdown=table-cell]]:text-left [&_[data-streamdown=table-cell]]:text-foreground/88 [&_[data-streamdown=table-cell]:last-child]:pr-0 [&_[data-streamdown=table-header-cell]:last-child]:pr-0 [&_[data-streamdown=table-row]:last-child_[data-streamdown=table-cell]]:border-b-0",
  "[&_[data-streamdown=mermaid-block]]:my-4 [&_[data-streamdown=mermaid-block]]:flex [&_[data-streamdown=mermaid-block]]:w-full [&_[data-streamdown=mermaid-block]]:min-w-0 [&_[data-streamdown=mermaid-block]]:gap-2 [&_[data-streamdown=mermaid-block]]:rounded-none [&_[data-streamdown=mermaid-block]]:border-0 [&_[data-streamdown=mermaid-block]]:bg-transparent [&_[data-streamdown=mermaid-block]]:p-0 [&_[data-streamdown=mermaid]]:my-0 [&_[data-streamdown=mermaid]]:block [&_[data-streamdown=mermaid]]:max-h-280px [&_[data-streamdown=mermaid]]:w-full [&_[data-streamdown=mermaid]]:min-w-0 [&_[data-streamdown=mermaid]]:overflow-hidden [&_[data-streamdown=mermaid]_svg]:mx-auto [&_[data-streamdown=mermaid]_svg]:block [&_[data-streamdown=mermaid]_svg]:h-auto [&_[data-streamdown=mermaid]_svg]:max-h-280px [&_[data-streamdown=mermaid]_svg]:max-w-full",
  "[&_.katex]:text-[1.04em] [&_.katex-display]:my-3.5 [&_.katex-display]:block [&_.katex-display]:max-w-full [&_.katex-display]:overflow-x-auto [&_.katex-display]:overflow-y-hidden [&_.katex-display]:px-1 [&_.katex-display]:py-1.5 [&_.katex-display]:text-center [&_[data-streamdown=image-wrapper]]:my-4 [&_[data-streamdown=image-wrapper]]:overflow-visible [&_[data-streamdown=image-wrapper]]:border-0 [&_[data-streamdown=image-wrapper]]:bg-transparent [&_[data-streamdown=image]]:block [&_[data-streamdown=image]]:max-h-136 [&_[data-streamdown=image]]:max-w-full [&_[data-streamdown=image]]:rounded-xl [&_[data-streamdown=image]]:border [&_[data-streamdown=image]]:border-border/60 [&_[data-streamdown=image]]:bg-muted/10 [&_[data-streamdown=image]]:object-contain [&_[data-streamdown=horizontal-rule]]:my-6 [&_[data-streamdown=horizontal-rule]]:border-border/45",
  "[&>*:first-child]:mt-0 [&>*:first-child>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&>*:last-child>*:last-child]:mb-0",
].join(" ");

export const THINKING_MARKDOWN_CLASS =
  "text-xs leading-6 text-muted-foreground/80 font-normal [&_p]:my-1 [&_p]:text-xs [&_p]:leading-6 [&_p]:text-muted-foreground/80 [&_p]:font-normal [&_strong]:font-medium [&_strong]:text-muted-foreground/95 [&_[data-streamdown=strong]]:font-medium [&_[data-streamdown=strong]]:text-muted-foreground/95 [&_[data-streamdown^=heading-]]:my-1 [&_[data-streamdown^=heading-]]:mb-0 [&_[data-streamdown^=heading-]]:text-xs [&_[data-streamdown^=heading-]]:leading-6 [&_[data-streamdown^=heading-]]:font-medium [&_[data-streamdown^=heading-]]:tracking-normal [&_[data-streamdown^=heading-]]:text-muted-foreground/90 [&_[data-streamdown=list-item]]:text-xs [&_[data-streamdown=list-item]]:leading-5 [&_[data-streamdown=list-item]]:font-normal [&_[data-streamdown=list-item]]:text-muted-foreground/80 [&_[data-streamdown=blockquote]]:my-1 [&_[data-streamdown=blockquote]]:border-l-0 [&_[data-streamdown=blockquote]]:pl-0 [&_[data-streamdown=blockquote]]:text-muted-foreground/75 [&_[data-streamdown=inline-code]]:bg-foreground/[0.03] [&_[data-streamdown=inline-code]]:text-xs [&_[data-streamdown=inline-code]]:text-muted-foreground/90 [&_[data-streamdown=code-block-body]]:bg-muted/20 [&_[data-streamdown=code-block-body]]:p-3 [&_[data-streamdown=code-block-body]]:text-xs";

export const DOCUMENT_MARKDOWN_CLASS =
  "text-sm leading-6 text-foreground/85 [&_p]:my-2.5 [&_p]:text-sm [&_p]:leading-6 [&_p]:text-foreground/85 [&_strong]:font-semibold [&_[data-streamdown=strong]]:font-semibold [&_[data-streamdown^=heading-]]:font-semibold [&_[data-streamdown^=heading-]]:tracking-tight [&_[data-streamdown=heading-1]]:mt-7 [&_[data-streamdown=heading-1]]:mb-3 [&_[data-streamdown=heading-1]]:text-lg [&_[data-streamdown=heading-2]]:mt-7 [&_[data-streamdown=heading-2]]:mb-2.5 [&_[data-streamdown=heading-2]]:text-base [&_[data-streamdown=heading-3]]:mt-6 [&_[data-streamdown=heading-3]]:mb-2 [&_[data-streamdown=heading-3]]:text-sm [&_[data-streamdown=list-item]]:pl-0.5 [&_[data-streamdown=list-item]]:text-sm [&_[data-streamdown=list-item]]:leading-6 [&_[data-streamdown=list-item]]:text-foreground/85 [&_[data-streamdown=list-item]>p]:my-0 [&_[data-streamdown=blockquote]]:my-4 [&_[data-streamdown=blockquote]]:border-l-2 [&_[data-streamdown=blockquote]]:border-border [&_[data-streamdown=blockquote]]:pl-3 [&_[data-streamdown=blockquote]]:text-foreground/75 [&_[data-streamdown=inline-code]]:rounded [&_[data-streamdown=inline-code]]:border [&_[data-streamdown=inline-code]]:border-border/50 [&_[data-streamdown=inline-code]]:bg-muted/65 [&_[data-streamdown=inline-code]]:px-1 [&_[data-streamdown=inline-code]]:py-0.5 [&_[data-streamdown=inline-code]]:text-[0.9em] [&_[data-streamdown=inline-code]]:text-foreground [&_[data-streamdown=code-block-body]]:rounded-lg [&_[data-streamdown=code-block-body]]:bg-muted/55 [&_[data-streamdown=code-block-body]]:p-3 [&_pre>code]:py-3! [&_pre>code]:text-xs [&_pre>code]:leading-5 [&_pre>code]:text-foreground/90 [&_[data-streamdown=horizontal-rule]]:my-7 [&_[data-streamdown=horizontal-rule]]:border-border/60";

export const PLAN_MARKDOWN_CLASS =
  "text-sm leading-1p72 text-foreground/90 [&_p]:my-1.5 [&_p]:text-sm [&_p]:leading-1p72 [&_p]:text-foreground/90 [&_[data-streamdown^=heading-]]:mt-4 [&_[data-streamdown^=heading-]]:mb-1.5 [&_[data-streamdown^=heading-]]:text-sm! [&_[data-streamdown^=heading-]]:leading-1p6 [&_[data-streamdown^=heading-]]:font-semibold [&_[data-streamdown^=heading-]]:tracking-0p01em [&_[data-streamdown=heading-1]]:text-sm! [&_[data-streamdown=heading-2]]:text-sm! [&>*:first-child]:mt-0 [&>*:first-child>*:first-child]:mt-0 [&_[data-streamdown=unordered-list]]:my-1.5 [&_[data-streamdown=unordered-list]]:ml-0 [&_[data-streamdown=unordered-list]]:space-y-1 [&_[data-streamdown=unordered-list]]:pl-[1.15rem] [&_[data-streamdown=ordered-list]]:my-1.5 [&_[data-streamdown=ordered-list]]:ml-0 [&_[data-streamdown=ordered-list]]:space-y-1 [&_[data-streamdown=ordered-list]]:pl-[1.15rem] [&_[data-streamdown=list-item]]:pl-0.5 [&_[data-streamdown=list-item]]:text-sm [&_[data-streamdown=list-item]]:leading-1p72 [&_[data-streamdown=list-item]]:text-foreground/90 [&_[data-streamdown=list-item]::marker]:text-muted-foreground/55 [&_[data-streamdown=ordered-list]>[data-streamdown=list-item]::marker]:font-medium [&_[data-streamdown=ordered-list]>[data-streamdown=list-item]::marker]:tabular-nums [&_[data-streamdown=inline-code]]:px-1 [&_[data-streamdown=inline-code]]:py-px [&_[data-streamdown=inline-code]]:text-xs [&_[data-streamdown=code-block]]:my-2.5 [&_[data-streamdown=code-block-body]]:rounded-lg [&_[data-streamdown=code-block-body]]:p-3 [&_[data-streamdown=code-block-body]]:text-xs [&_[data-streamdown=blockquote]]:my-2 [&_[data-streamdown=blockquote]]:border-l-2 [&_[data-streamdown=blockquote]]:border-border/50 [&_[data-streamdown=blockquote]]:pl-3 [&_[data-streamdown=blockquote]]:text-muted-foreground dark:[&_[data-streamdown=blockquote]]:border-white/[0.12] [&_[data-streamdown=horizontal-rule]]:my-3.5 [&_[data-streamdown=horizontal-rule]]:border-border/35";

export const RELEASE_NOTES_MARKDOWN_CLASS =
  "text-xs leading-relaxed text-muted-foreground [&_p]:my-2 [&_p]:text-xs [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_[data-streamdown=heading-1]]:mt-3 [&_[data-streamdown=heading-1]]:mb-2 [&_[data-streamdown=heading-1]]:text-sm [&_[data-streamdown=heading-1]]:font-semibold [&_[data-streamdown=heading-2]]:mt-3 [&_[data-streamdown=heading-2]]:mb-2 [&_[data-streamdown=heading-2]]:text-sm [&_[data-streamdown=heading-2]]:font-semibold [&_[data-streamdown=heading-3]]:mt-3 [&_[data-streamdown=heading-3]]:mb-1.5 [&_[data-streamdown=heading-3]]:text-xs [&_[data-streamdown=heading-3]]:font-semibold [&_[data-streamdown=unordered-list]]:my-2 [&_[data-streamdown=unordered-list]]:ml-0 [&_[data-streamdown=unordered-list]]:list-disc [&_[data-streamdown=unordered-list]]:space-y-1 [&_[data-streamdown=unordered-list]]:pl-5 [&_[data-streamdown=ordered-list]]:my-2 [&_[data-streamdown=ordered-list]]:ml-0 [&_[data-streamdown=ordered-list]]:list-decimal [&_[data-streamdown=ordered-list]]:space-y-1 [&_[data-streamdown=ordered-list]]:pl-5 [&_[data-streamdown=list-item]]:pl-1 [&_[data-streamdown=list-item]]:text-xs [&_[data-streamdown=list-item]]:leading-relaxed [&_[data-streamdown=list-item]]:text-muted-foreground [&_[data-streamdown=blockquote]]:my-2 [&_[data-streamdown=blockquote]]:border-l-2 [&_[data-streamdown=blockquote]]:border-border/70 [&_[data-streamdown=blockquote]]:pl-3 [&_[data-streamdown=blockquote]]:text-xs [&_[data-streamdown=blockquote]]:text-muted-foreground [&_[data-streamdown=inline-code]]:rounded [&_[data-streamdown=inline-code]]:border [&_[data-streamdown=inline-code]]:border-border/50 [&_[data-streamdown=inline-code]]:bg-muted/60 [&_[data-streamdown=inline-code]]:px-1 [&_[data-streamdown=inline-code]]:py-0.5 [&_[data-streamdown=inline-code]]:font-mono [&_[data-streamdown=inline-code]]:text-xs [&_[data-streamdown=inline-code]]:text-foreground/90";
